// <auto-generated />
using BaseApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseApi.Migrations
{
    [DbContext(typeof(mycontext))]
    [Migration("20230214090328_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseApi.Model.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("role")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("UserT");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            address = "tehran",
                            age = 27,
                            name = "kananiHassan",
                            role = false
                        },
                        new
                        {
                            id = 2L,
                            address = "Ahvaz",
                            age = 14,
                            name = "Aref",
                            role = false
                        },
                        new
                        {
                            id = 3L,
                            address = "Khorasan",
                            age = 17,
                            name = "Ali",
                            role = false
                        },
                        new
                        {
                            id = 4L,
                            address = "iran",
                            age = 23,
                            name = "Mehdi",
                            role = false
                        },
                        new
                        {
                            id = 5L,
                            address = "boujnord",
                            age = 25,
                            name = "Reza",
                            role = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
